"""
Trading Card Print Shop — Production Analysis (V2.1 - Customer & Path-Safe)
=============================================
Portability: Works on Mac/PC. Auto-locates CSV based on script directory.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import subprocess
import warnings
warnings.filterwarnings("ignore")

# ── 1. DYNAMIC PATH RESOLUTION ────────────────────────────────────────────────
# This ensures the script looks in its own folder, not the base Documents folder
script_dir = os.path.dirname(os.path.abspath(__file__))

# We search for the most recent results CSV generated by the engine
csv_files = [f for f in os.listdir(script_dir) if f.startswith("results_") and f.endswith(".csv")]
if not csv_files:
    print(f"❌ Error: No 'results_*.csv' files found in {script_dir}")
    sys.exit(1)

# Sort by date to grab the newest one
csv_files.sort(key=lambda x: os.path.getmtime(os.path.join(script_dir, x)), reverse=True)
CSV_FILE = os.path.join(script_dir, csv_files[0])

# Styling
BLUE, MED, LIGHT, RED, ORANGE, GREEN = "#1F4E79", "#2E75B6", "#BDD7EE", "#C00000", "#ED7D31", "#375623"
plt.rcParams.update({
    "font.family": "DejaVu Sans", "axes.spines.top": False, "axes.spines.right": False,
    "axes.facecolor": "#FAFAFA", "figure.facecolor": "white",
})

# ── 2. LOAD & ANALYZE ─────────────────────────────────────────────────────────
df = pd.read_csv(CSV_FILE)
print(f"✅ Analysis Engine Loaded: {CSV_FILE}")
print(f"Processing {len(df):,} High-Volume Jobs...")

print("\n=== EXECUTIVE PRODUCTION SUMMARY ===")
print(f"Total Revenue:          ${df['revenue'].sum():>12,.0f}")
print(f"Total Gross Profit:     ${df['gross_profit'].sum():>12,.0f}")
print(f"Avg Gross Margin:       {df['gross_margin_pct'].mean():>11.1f}%")
print(f"Quality Pass Rate:      {df['quality_pass'].mean():>11.1%}")

print("\n--- Customer Profitability Profile ---")
# Grouping by customer to see who is actually making money
cust_summary = df.groupby("customer_id").agg({
    "job_id": "count",
    "gross_margin_pct": "mean",
    "waste_pct": "mean",
    "revenue": "sum"
}).rename(columns={"job_id": "Jobs", "gross_margin_pct": "Margin %", "waste_pct": "Waste %", "revenue": "Total Rev"})
print(cust_summary.round(2))

# ── 3. VISUALIZATION ──────────────────────────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(15, 10))
fig.suptitle(f"Operational Intelligence: {os.path.basename(CSV_FILE)}", fontsize=16, fontweight="bold", color=BLUE)

# CHART A: Customer Margin vs Waste
cust_ids = df['customer_id'].unique()
margins = [df[df['customer_id'] == c]['gross_margin_pct'].mean() for c in cust_ids]
axes[0,0].bar(cust_ids, margins, color=[MED, ORANGE], edgecolor="white", width=0.5)
axes[0,0].set_title("Avg Gross Margin % by Customer", fontweight="bold")

# CHART B: Press Waste Performance (Spotting the Older Presses)
presses = ["SF-1", "SF-2", "SF-3", "SF-4", "PF-1", "PF-2"]
press_waste = [df[df['press'] == p]['waste_pct'].mean() for p in presses]
axes[0,1].bar(presses, press_waste, color=[MED, MED, RED, MED, GREEN, RED], width=0.6)
axes[0,1].set_title("Waste % by Press (Red = Older/Penalty)", fontweight="bold")

# CHART C: Cost Drivers (Showing Volume Impact)
cost_cols = ["paper_cost", "press_cost", "ink_cost", "plate_cost", "finishing_cost"]
totals = [df[c].sum() for c in cost_cols]
axes[1,0].pie(totals, labels=["Paper", "Labor", "Ink", "Plates", "Finish"], autopct='%1.1f%%', colors=[RED, BLUE, GREEN, ORANGE, LIGHT])
axes[1,0].set_title("Total Shop Spend Distribution", fontweight="bold")

# CHART D: Quality Pass Rate by Shift
shifts = ["Red Day", "Red Night", "Black Day", "Black Night"]
q_pass = [df[df['shift'] == s]['quality_pass'].mean() for s in shifts]
axes[1,1].bar(shifts, q_pass, color=[BLUE, LIGHT, BLUE, LIGHT])
axes[1,1].set_ylim(0, 1.0)
axes[1,1].set_title("Quality Pass Rate by Shift", fontweight="bold")

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
output_img = os.path.join(script_dir, "production_intelligence_v2.png")
plt.savefig(output_img, dpi=150)

# ── 4. AUTO-OPEN (Portability Logic) ──────────────────────────────────────────
print(f"\n✅ Analysis complete. Chart saved to: {output_img}")
if sys.platform == "win32":
    os.startfile(output_img)
else:
    subprocess.call(["open", output_img])